"use client";

import { useEffect, useState } from "react";

type Preferences = { appearance: "dark" | "museum" | "system"; motion: "cinematic" | "balanced" | "reduced"; density: "comfortable" | "compact" | "immersive"; contrast: boolean; largeUi: boolean };
const defaults: Preferences = { appearance: "dark", motion: "balanced", density: "comfortable", contrast: false, largeUi: false };
function applyPreferences(value: Preferences) { const root = document.documentElement; root.dataset.appearance = value.appearance; root.dataset.motion = value.motion; root.dataset.galleryDensity = value.density; root.dataset.contrast = value.contrast ? "high" : "standard"; root.dataset.uiSize = value.largeUi ? "large" : "standard"; }

export function DisplayPreferences() {
  const [preferences, setPreferences] = useState<Preferences>(defaults);
  useEffect(() => { const timer = window.setTimeout(() => { try { const stored = JSON.parse(window.localStorage.getItem("giggle.display") ?? "null") as Partial<Preferences> | null; const next = { ...defaults, ...stored }; setPreferences(next); applyPreferences(next); } catch { applyPreferences(defaults); } }, 0); return () => window.clearTimeout(timer); }, []);
  function update<K extends keyof Preferences>(key: K, value: Preferences[K]) { const next = { ...preferences, [key]: value }; setPreferences(next); applyPreferences(next); window.localStorage.setItem("giggle.display", JSON.stringify(next)); }
  return <div className="space-y-8"><ChoiceGroup title="Appearance" description="Choose how the gallery is lit on this device." value={preferences.appearance} options={[["dark","Dark"],["museum","Museum Light"],["system","System"]]} onChange={(value) => update("appearance", value as Preferences["appearance"])} /><ChoiceGroup title="Motion" description="Control cinematic movement without affecting forms or checkout." value={preferences.motion} options={[["cinematic","Cinematic"],["balanced","Balanced"],["reduced","Reduced"]]} onChange={(value) => update("motion", value as Preferences["motion"])} /><ChoiceGroup title="Gallery density" description="Set how much artwork appears at once." value={preferences.density} options={[["comfortable","Comfortable"],["compact","Compact"],["immersive","Immersive"]]} onChange={(value) => update("density", value as Preferences["density"])} /><section><h3 className="text-lg font-semibold">Accessibility</h3><p className="mt-1 text-sm text-white/45">These preferences stay on this device.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Toggle label="Increased contrast" checked={preferences.contrast} onChange={(value) => update("contrast", value)} /><Toggle label="Larger interface text" checked={preferences.largeUi} onChange={(value) => update("largeUi", value)} /></div></section></div>;
}
function ChoiceGroup({ title, description, value, options, onChange }: { title: string; description: string; value: string; options: Array<[string, string]>; onChange: (value: string) => void }) { return <section><h3 className="text-lg font-semibold">{title}</h3><p className="mt-1 text-sm text-white/45">{description}</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{options.map(([key, label]) => <button key={key} type="button" aria-pressed={value === key} onClick={() => onChange(key)} className={`rounded-xl border px-4 py-4 text-left text-sm transition ${value === key ? "border-[#5577FF] bg-[#5577FF]/10 text-white" : "border-white/10 bg-white/[.025] text-white/55 hover:border-white/25"}`}>{label}</button>)}</div></section>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[.025] px-4 py-4 text-left text-sm"><span>{label}</span><span className={`relative h-6 w-11 rounded-full transition ${checked ? "bg-[#5577FF]" : "bg-white/15"}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition ${checked ? "left-6" : "left-1"}`} /></span></button>; }
