import Link from "next/link";
import { auth } from "@/auth";
import { EmailSettings } from "@/app/account/EmailSettings";
import { AccountShell } from "@/app/components/AccountShell";
import { GalleryShell } from "@/app/components/GalleryShell";
import { DisplayPreferences } from "@/app/settings/DisplayPreferences";
import { getIdentityOverview } from "@/lib/identity/service";

export const dynamic = "force-dynamic";
export default async function SettingsPage() {
  const session = await auth(); if (!session?.user) return null;
  const identity = await getIdentityOverview(session.user.id); const primaryEmail = identity?.email ?? session.user.email ?? "";
  return <GalleryShell><AccountShell active="Settings"><header><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#C6A66A]">Your account</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Settings</h1><p className="mt-3 max-w-2xl text-white/50">Identity, display and accessibility preferences—kept separate from shopping and selling.</p></header><div className="mt-8 space-y-6"><section id="account" className="rounded-2xl border border-white/10 bg-[#0C1018] p-6 sm:p-8"><h2 className="text-2xl font-semibold">Account & identity</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Info label="Display name" value={identity?.displayName ?? identity?.name ?? session.user.name ?? "Collector"} /><Info label="Primary email" value={primaryEmail || "Not available"} /><Info label="Google connection" value={identity?.providers.includes("google") ? "Connected" : "Not connected"} /><Info label="Account role" value={identity?.role ?? session.user.role} /></div>{identity && primaryEmail ? <EmailSettings primaryEmail={primaryEmail} primaryEmailVerified={Boolean(identity.emailVerified)} contactEmail={identity.contactEmail} contactEmailVerified={Boolean(identity.contactEmailVerifiedAt)} /> : null}</section><section id="appearance" className="rounded-2xl border border-white/10 bg-[#0C1018] p-6 sm:p-8"><DisplayPreferences /></section><section id="notifications" className="rounded-2xl border border-white/10 bg-[#0C1018] p-6 sm:p-8"><h2 className="text-2xl font-semibold">Notifications</h2><p className="mt-2 text-sm leading-relaxed text-white/50">Order, auction, follow and seller events appear in your persisted notification center. Delivery controls are not shown because per-channel preferences are not yet supported.</p><Link href="/notifications" className="button-outline mt-5">Open notification center</Link></section><section id="security" className="rounded-2xl border border-white/10 bg-[#0C1018] p-6 sm:p-8"><h2 className="text-2xl font-semibold">Security & connected accounts</h2><p className="mt-2 text-sm leading-relaxed text-white/50">Your primary sign-in is managed by Google. Giggle Gallery does not store a password or expose unsupported privacy controls.</p><div id="connections" className="mt-5 rounded-xl border border-white/10 p-4 text-sm"><span className="text-white/45">Google account</span><strong className="float-right">{identity?.providers.includes("google") ? "Connected" : "Not connected"}</strong></div></section></div></AccountShell></GalleryShell>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs uppercase tracking-[.14em] text-white/35">{label}</p><p className="mt-2 break-words text-sm text-white/80">{value}</p></div>; }
